export const EIconName = {
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  Google: 'Google',
  Facebook: 'Facebook',
  EyeClosed: 'EyeClosed',
  Eye: 'Eye',
  Calendar: 'Calendar',
  AngleDown: 'AngleDown',
  AngleLeft: 'AngleLeft',
  AngleRight: 'AngleRight',
  Copy: 'Copy',
  MinusCircle: 'MinusCircle',
  Bars: 'Bars',
  Close: 'Close',
  CheckCircle: 'CheckCircle',
  Clock: 'Clock',
  Info: 'Info',
  Memo: 'Memo',
  Challenge: 'Challenge',
  Knife: 'Knife',
  Cup: 'Cup',
};

export const EIconColor = {
  BLACK: '#000',
  WHITE: '#fff',
  COD_GRAY: '#1E1E1E',
  BLUE_RIBBON: '#1964FF',
  ELECTRIC_VIOLET: '#6A36FF',
  PERSIAN_GREEN: '#00AF89',
  RED_ORANGE: '#FF2E2E',
  BG: '#F2F6F8',
};
